# #######################################################################################
#######                            HYPRLAND CONGIG                                #######
# #######################################################################################


# You can split this configuration into multiple files
# Create your files separately and then link them


# Configuration files:
source = ~/.config/hypr/config/aesthetic.conf               # Control visual settings like themes and wallpapers.
source = ~/.config/hypr/config/animation.conf               # Control visual settings like themes and wallpapers.
source = ~/.config/hypr/config/autostart.conf               # Define applications to start on startup.
source = ~/.config/hypr/config/environment.conf             # Set environment variable and system behaviours.
source = ~/.config/hypr/config/input-rules.conf             # Specify input device roles.
source = ~/.config/hypr/config/keybindings.conf             # Define custom keybindings.
source = ~/.config/hypr/config/layout.conf                  # Control visual settings like themes and wallpapers.
source = ~/.config/hypr/config/misc.conf                    # Miscellenous configurations
source = ~/.config/hypr/config/monitor.conf                 # Configure monitor layout and configuration.
source = ~/.config/hypr/config/permissions.conf             # Define workspace rules and layout.
source = ~/.config/hypr/config/variable.conf                # General variables affecting the system.
source = ~/.config/hypr/config/window-rules.conf            # Window specific rules for behaviour and appearance.
source = ~/.config/hypr/config/layer-rules.conf             # Layer-rule specific rules for behaviour and appearance.





                                    # Refer to the wiki for more information.
                                    # https://wiki.hypr.land/Configuring/

